export type Doctor = {
  id: string;
  name: string;
  role: string;
  exp: string;
  specialization: string;
  education: string;
  schedule: string;
  price: string;
  rating: number;
  img: string;
  about: string;
  services: string[];
  achievements: string[];
  languages?: string[];
  tags?: string[];
  nextSlots?: string[];
  prices?: { title: string; description?: string; amount: string }[];
  reviews?: { author: string; rating: number; text: string }[];
};

export const doctors: Doctor[] = [
  {
    id: "1",
    name: "",
    role: "Терапевт",
    exp: "10+ лет опыта",
    specialization: "Терапевт",
    education: "—",
    schedule: "Пн–Пт: 09:00–18:00",
    price: "от 7 000 тг",
    rating: 4.8,
    img: "/doctors/terapevt.png",
    about: "Прием и лечение внутренних заболеваний. Профилактика и наблюдение.",
    services: ["Консультация терапевта", "План лечения", "Профилактический осмотр"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Терапия"],
  },
  {
    id: "2",
    name: "",
    role: "Невролог",
    exp: "10+ лет опыта",
    specialization: "Невролог",
    education: "—",
    schedule: "Пн–Сб: 10:00–18:00",
    price: "от 10 000 тг",
    rating: 4.8,
    img: "/doctors/nevropotolog.png",
    about: "Диагностика и лечение заболеваний нервной системы.",
    services: ["Консультация невролога", "Подбор терапии"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Неврология"],
  },
  {
    id: "3",
    name: "",
    role: "Офтальмолог",
    exp: "8+ лет опыта",
    specialization: "Офтальмолог",
    education: "—",
    schedule: "Вт–Сб: 10:00–19:00",
    price: "от 8 000 тг",
    rating: 4.7,
    img: "/doctors/oftalmolog.png",
    about: "Диагностика и лечение заболеваний органов зрения.",
    services: ["Осмотр зрения", "Подбор лечения"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Офтальмология"],
  },
  {
    id: "4",
    name: "",
    role: "Гинеколог",
    exp: "10+ лет опыта",
    specialization: "Гинеколог",
    education: "—",
    schedule: "Пн–Пт: 11:00–19:00",
    price: "от 9 000 тг",
    rating: 4.8,
    img: "/doctors/ginekolog.png",
    about: "Женское здоровье, профилактика и лечение.",
    services: ["Консультация гинеколога", "Диагностика"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Гинекология"],
  },
  {
    id: "5",
    name: "",
    role: "Оториноларинголог",
    exp: "10+ лет опыта",
    specialization: "Оториноларинголог (ЛОР)",
    education: "—",
    schedule: "Пн–Сб: 10:00–18:00",
    price: "от 9 000 тг",
    rating: 4.7,
    img: "/doctors/оториноларинголог.png",
    about: "Лечение заболеваний уха, горла и носа.",
    services: ["Консультация ЛОР", "Медикаментозное лечение"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["ЛОР"],
  },
  {
    id: "6",
    name: "",
    role: "Рентген-лаборант",
    exp: "5+ лет опыта",
    specialization: "Рентген-лаборант",
    education: "—",
    schedule: "Пн–Пт: 09:00–18:00",
    price: "—",
    rating: 4.6,
    img: "/doctors/rentgen_laborant.png",
    about: "Проведение рентгенологических исследований.",
    services: ["Проведение рентген-снимков"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Диагностика"],
  },
  {
    id: "7",
    name: "",
    role: "Рентген-лаборант",
    exp: "5+ лет опыта",
    specialization: "Рентген-лаборант",
    education: "—",
    schedule: "Пн–Пт: 09:00–18:00",
    price: "—",
    rating: 4.6,
    img: "/doctors/rentgen_laborant_2.png",
    about: "Проведение рентгенологических исследований.",
    services: ["Проведение рентген-снимков"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Диагностика"],
  },
  {
    id: "8",
    name: "",
    role: "Лаборант",
    exp: "5+ лет опыта",
    specialization: "Лаборант",
    education: "—",
    schedule: "Пн–Сб: 09:00–17:00",
    price: "—",
    rating: 4.6,
    img: "/doctors/laborant.png",
    about: "Забор и подготовка биоматериала, лабораторные процедуры.",
    services: ["Лабораторные процедуры"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Лаборатория"],
  },
  {
    id: "9",
    name: "",
    role: "Врач-бактериолог",
    exp: "8+ лет опыта",
    specialization: "Врач-бактериолог",
    education: "—",
    schedule: "Пн–Пт: 10:00–18:00",
    price: "—",
    rating: 4.7,
    img: "/doctors/Vrach_bakteriolog.png",
    about: "Микробиологические исследования и интерпретация результатов.",
    services: ["Бактериологические исследования"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Лаборатория"],
  },
  {
    id: "10",
    name: "",
    role: "Медицинская сестра",
    exp: "5+ лет опыта",
    specialization: "Медицинская сестра",
    education: "—",
    schedule: "Пн–Сб: 09:00–18:00",
    price: "—",
    rating: 4.6,
    img: "/doctors/medicinskaia_sestra.png",
    about: "Процедуры и помощь врачу, забор анализов.",
    services: ["Процедуры", "Забор анализов"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Медсестра"],
  },
  {
    id: "11",
    name: "",
    role: "Медицинская сестра-лаборант",
    exp: "5+ лет опыта",
    specialization: "Медицинская сестра-лаборант",
    education: "—",
    schedule: "Пн–Сб: 09:00–18:00",
    price: "—",
    rating: 4.6,
    img: "/doctors/Medicinskaia_sestra.laborant.png",
    about: "Выполнение процедур и лабораторных манипуляций.",
    services: ["Процедуры", "Лабораторные манипуляции"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Медсестра", "Лаборатория"],
  },
  {
    id: "12",
    name: "",
    role: "Терапевт ВОП, маммолог",
    exp: "10+ лет опыта",
    specialization: "Терапевт ВОП, маммолог",
    education: "—",
    schedule: "Пн–Пт: 10:00–18:00",
    price: "от 8 000 тг",
    rating: 4.7,
    img: "/doctors/terapevt.VOP.mamolog.png",
    about: "Комплексный прием врача общей практики и маммолога.",
    services: ["Консультация ВОП", "Консультация маммолога"],
    achievements: ["—"],
    languages: ["Русский"],
    tags: ["Терапия", "Маммология"],
  },
];

export function getDoctorById(id: string): Doctor | undefined {
  return doctors.find((d) => d.id === id);
}

export function getAllDoctorIds(): string[] {
  return doctors.map((d) => d.id);
}


